-- Additional BMO questions from detailed screenshots

-- Insert additional detailed BMO questions
INSERT INTO questions (category_id, question_number, question_text, answer_text, keywords) VALUES 

-- General - Change of Scope with detailed options
((SELECT id FROM categories WHERE name = 'BMO General'), '3.0', 'Change of Scope of Relationship - Since your last Due Diligence assessment, has there been a change in your organization or the products or services provided to BMO? Select all that apply: Change of ownership in the organization, Delivering products or services TO a different Country, Delivering products or services FROM a different Country, Products and/or services added or removed, No Change in Scope of products or services provided', 'Multiple choice options available for selection', 'change scope relationship due diligence assessment organization ownership country products services added removed'),

-- Legal and Regulatory Framework - Governance Structure detailed
((SELECT id FROM categories WHERE name = 'BMO Legal and Regulatory Framework'), '4.0', 'Legal and Regulatory Framework - Select all that are applicable to your organization''s governance structure. Governance Structure options: Independent Board of Directors, Independent audit group, Issues Management Policy, Material Issues/breaches reported to the BOD, Complaints Management Program, None of the above', 'Multiple selection options for governance structure', 'legal regulatory framework governance structure independent board directors audit group issues management policy BOD complaints program'),

-- Legal and Regulatory Framework - Legal Framework detailed
((SELECT id FROM categories WHERE name = 'BMO Legal and Regulatory Framework'), '4.0', 'Select all that are applicable to your organization''s Legal & Regulatory Framework: Inventory of all laws and regulations applicable to the company, Compliance report to ensure all laws and regulations met, Data privacy assessments or ongoing monitoring relating to privacy controls, Domain Leads (i.e. Regulatory or Compliance Officers) that keep track of HR regulations/regulation changes in the jurisdiction(s) in which you operate and ensure these changes are appropriately implemented by the respective business units to ensure compliance, Company does not have a Legal & Regulatory framework', 'Multiple selection options for legal and regulatory framework', 'legal regulatory framework inventory laws regulations compliance report data privacy assessments domain leads officers HR jurisdiction business units'),

-- Legal and Regulatory Framework - Regulatory Oversight
((SELECT id FROM categories WHERE name = 'BMO Legal and Regulatory Framework'), '4.0', 'Is your organization subject to regulatory agency oversight? Regulatory Oversight options: Yes, No', 'Yes/No selection for regulatory oversight', 'organization subject regulatory agency oversight yes no'),

-- Legal and Regulatory Framework - No Policies Explanation
((SELECT id FROM categories WHERE name = 'BMO Legal and Regulatory Framework'), '4.0.1', 'Legal and Regulatory Framework - No Policies and/or Procedures - Explain why you do not maintain any policies and procedures.', 'Not Applicable', 'legal regulatory framework no policies procedures explain maintain not applicable'),

-- Governance Structure Artifacts
((SELECT id FROM categories WHERE name = 'BMO Governance Structure'), '4.1.1', 'Governance Structure Artifacts - For the Governance Structure question, provide supporting artifacts for each item selected as evidence.', 'Upload supporting artifacts required', 'governance structure artifacts evidence supporting documents upload required'),

-- Incidents and Findings - Detailed incident types
((SELECT id FROM categories WHERE name = 'BMO Incidents and Findings'), '5.0', 'Incidents and Findings - Since your last assessment, has your organization or any subcontractor encountered any of the following issues or incidents? Select all that apply: An unauthorized or improper collection, use, disclosure of Personal Information in the last 24 months, Physical or Information Security Incidents / Privacy breach, Identified material data loss (i.e. data corruption or Integrity Issues) that impacted Service Level Agreements to BMO, Material issues or changes related to Digital, AI, or Robotic Process Automation (RPA), Emerging Technology applications or services that impact the trustworthiness rating/assessment (i.e. Fair, Accountable, Transparent, Trusted) or the SLA, You or your directors, officers or employees have been suspected of/investigated for violating anti-bribery and anti-corruption laws by a court, public agency, or regulatory body, Privacy-related regulatory findings or privacy-related legal action taken against your firm, Experienced outages or service disruptions in the last 12 months, None of the above', 'Multiple selection options for incidents and findings', 'incidents findings assessment organization subcontractor unauthorized improper collection personal information security incidents privacy breach data loss corruption integrity service level agreements digital AI robotic process automation RPA emerging technology trustworthiness fair accountable transparent trusted SLA anti-bribery corruption regulatory findings legal action outages service disruptions'),

-- Training - Detailed training subjects
((SELECT id FROM categories WHERE name = 'BMO Training'), '6.0', 'Training - Does your organization maintain a mandatory annual training curriculum on any of the following subjects? Select all that apply: Fraud, Fair Credit Reporting Act, Privacy, Information Security, and/or Cybersecurity Awareness, Ethical AI Awareness (i.e. Fair, Accountable, Transparent, Trusted), None of the above', 'Multiple selection options for training subjects', 'training organization mandatory annual curriculum fraud fair credit reporting act privacy information security cybersecurity awareness ethical AI fair accountable transparent trusted'),

-- Subcontractor Information - Detailed description
((SELECT id FROM categories WHERE name = 'BMO Subcontractor'), '7.0', 'Subcontractor Information - Depending on your specific contractual agreement, BMO''s Third-Parties may use Subcontractors (your organization''s Third-Parties) to deliver some of the products or services to BMO. BMO requires awareness of your use of Subcontractors. Subcontractors are broadly defined to include the firm Subcontractors, consultants, agents, sales representatives or other parties your organization might engage to deliver the products or services to BMO. Throughout this program Subcontractor refers to your organization''s Third-Parties. Please only consider Subcontractors used in the delivery of products or services to BMO.', 'Information about subcontractor requirements and definitions', 'subcontractor information contractual agreement BMO third parties deliver products services awareness consultants agents sales representatives definition'),

-- Not Using Subcontractors - Detailed question
((SELECT id FROM categories WHERE name = 'BMO Subcontractor'), '7.1.10', 'Not Using Subcontractors - We currently have on file that you are not using Subcontractors to deliver the products or services to BMO. Since the last review have you retained or hired parties such as Subcontractors, consultants, agents or sales representatives in connection with providing the products or services to BMO? Options: Yes, No', 'Yes/No selection for subcontractor usage', 'not using subcontractors file deliver products services BMO retained hired parties consultants agents sales representatives yes no'),

-- Locations - Review/Update Third-Party and Subcontractor Addresses
((SELECT id FROM categories WHERE name = 'BMO Locations'), '8.0.1', 'Review/Update Third-Party and Subcontractor Addresses - Shown below in section 8.2 are location/address details for all of your organization and subcontractor Primary and Backup locations used to provide the products or services to BMO under this arrangement. Please review the information within the location object by clicking on edit and make any updates as necessary.', 'Review and update location/address details for organization and subcontractor locations', 'review update third party subcontractor addresses location details organization primary backup locations products services BMO arrangement edit updates'),

-- Subcontractor Addresses - Primary and Backup sites
((SELECT id FROM categories WHERE name = 'BMO Locations'), '8.0.3', 'Review/Update Subcontractor Addresses - A Subcontractor''s product or service has a degree of importance to your business operations utilized under this arrangement or is an outsourced business process in the provision of the product/service arrangement to BMO. How many Primary Subcontractor sites are there in total to provide products or services to BMO under this contractual agreement? How many Backup Subcontractor sites are there in total to provide products or services to BMO under this contractual agreement?', 'Primary Subcontractor Sites: 0, Backup Subcontractor Sites: 0', 'review update subcontractor addresses product service degree importance business operations outsourced process primary backup sites contractual agreement BMO total'),

-- Third-Party Addresses - Primary and Backup sites
((SELECT id FROM categories WHERE name = 'BMO Locations'), '8.0.4', 'Review/Update Third-Party Addresses - How many Primary Third-Party sites (for your organization, inclusive of headquarter location) are there in total to provide products or services to BMO under this contractual agreement? How many Backup Third-Party sites (for your organization) are there in total to provide products or services to BMO under this contractual agreement?', 'Primary Third-Party Sites: 1, Backup Third-Party Sites: 0', 'review update third party addresses primary backup sites organization headquarter location contractual agreement BMO total'),

-- Location/Address Listing - Detailed instructions
((SELECT id FROM categories WHERE name = 'BMO Locations'), '8.2', 'Location/Address Listing - A file must be completed for each location indicated in sections 8.0.1 and 8.0.4. You can do the following for the locations listed below. For each location/address answer all required questions: Add new locations by clicking the Add button, Edit an existing location by clicking on the list, Do not delete any locations. If they are no longer used set their status to Inactive, Do not use Inactive or any other you have changed or added in the current session only, Please review the information within the location object by clicking on Edit and make any updates as necessary. Existing locations being entered should reflect all previous controls that were last attested to. When entering existing or new Third-Party or Subcontractor locations it is encouraged to reach out to building management and/or the Third-Party or Subcontractor''s internal Physical Security department to ensure Physical Security controls are accurately captured. Failure to provide sufficient controls will result in UNSATISFACTORY or NEEDS IMPROVEMENT ratings and mitigation will be required via control implementation. When entering a location all fields are mandatory. Failure to provide a response to all location fields will result in an UNSATISFACTORY or NEEDS IMPROVEMENT ratings.', 'Detailed instructions for location management including Corporate Headquarters and Woodridge Software locations with specific requirements for editing, status management, and mandatory field completion', 'location address listing file completed sections add new locations edit existing delete status inactive review information mandatory fields corporate headquarters woodridge software physical security controls unsatisfactory needs improvement ratings mitigation'),

-- Location changes questions
((SELECT id FROM categories WHERE name = 'BMO Locations'), '8.2', 'Did you make any changes to your organization''s primary or backup location where products/services are provided to BMO? Options: Yes, No. Did you make any changes to Subcontractor''s primary or backup location where products/services are provided to BMO? Options: Yes, No. Have you provided all the Primary location(s), including your organization''s headquarters and, if applicable, the Backup location(s) from where your organization or Subcontractors provide products/services to BMO? Options: Yes, No', 'Yes/No selections for location changes and completeness verification', 'changes organization primary backup location products services provided BMO subcontractor headquarters location completeness verification yes no'),

-- Risk Assessment categories
((SELECT id FROM categories WHERE name = 'BMO Risk Assessment'), '12.0.1', 'ABAC Risk - Anti Bribery And Corruption (ABAC) is not in scope for this Assessment', 'Anti Bribery And Corruption (ABAC) is not in scope for this Assessment', 'ABAC risk anti bribery corruption not in scope assessment'),

((SELECT id FROM categories WHERE name = 'BMO Risk Assessment'), '13.0.1', 'AML Risk - Anti Money Laundering Risk (AML) is not in scope for this Assessment', 'Anti Money Laundering Risk (AML) is not in scope for this Assessment', 'AML risk anti money laundering not in scope assessment'),

((SELECT id FROM categories WHERE name = 'BMO Risk Assessment'), '14.0.1', 'BCM Risk - Business Continuity Risk (BCM) is not in scope for this Assessment', 'Business Continuity Risk (BCM) is not in scope for this Assessment', 'BCM risk business continuity not in scope assessment'),

-- Fraud Risk - Detailed definition
((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.2', 'Fraud Risk - Fraud Risk is when a Third-Party is able to use illegal and deceptive means to obtain BMO''s money, assets, property, information or other gains. Fraud risk is present when Third-Parties have access premises, employees, customers, and information. Failure of Third-Parties to meet regulatory requirements or breaching contract terms for other risk areas can result in a fraudulent scenario.', 'Fraud Risk definition explaining illegal and deceptive means to obtain BMO assets', 'fraud risk third party illegal deceptive means obtain BMO money assets property information gains access premises employees customers regulatory requirements breaching contract fraudulent scenario'),

-- Fraud Risk Questions - Background check and ongoing process
((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.1', 'Fraud Risk Questions - Does your organization maintain a background check policy, procedure, or standard that requires the performance of background checks on all employees and subcontractors? Options: Yes, No. Does your organization have an ongoing process to ensure that employees have not been convicted of, placed in a pre-trial diversion program, or accepted responsibility (e.g., through a plea bargain) for any crime involving fraud, theft, dishonesty, breach of trust or a violent act since the hiring background check was completed? Options: Yes, No', 'Yes/No selections for background check policy and ongoing process', 'fraud risk questions organization maintain background check policy procedure standard performance employees subcontractors ongoing process convicted pre-trial diversion program accepted responsibility plea bargain crime fraud theft dishonesty breach trust violent act hiring yes no'),

-- Fraud Management Policy and Training
((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.1', 'Does your organization have Policies/Processes/Training for managing fraud (i.e., does your firm have a Code of Ethics/Code of Conduct or a Fraud Management Policy)? Options: Yes, No. Does your organization currently have any of these processes in place? Select all that apply: Logical Access, Segregation of Duty, Supervisory Review, Reconciliation, None of the Above', 'Yes/No for fraud management policies and multiple selection for processes in place', 'organization policies processes training managing fraud code ethics conduct fraud management policy logical access segregation duty supervisory review reconciliation none above yes no'),

-- Fraud - Background Check Policies
((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.1.1', 'Fraud - Background Check Policies - Please provide evidence of the Background check policy, procedure, or standard that covers employees and Subcontractors.', 'Upload required for background check policy evidence', 'fraud background check policies provide evidence policy procedure standard covers employees subcontractors upload required'),

-- Fraud - Management Policy & Training Curriculum
((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.1.3', 'Fraud - Management Policy & Training Curriculum - Please provide your Fraud Management Policy and Fraud Training Curriculum.', 'Upload required for fraud management policy and training curriculum', 'fraud management policy training curriculum provide upload required'),

-- Detecting Fraudulent Activity
((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.1.5', 'Detecting Fraudulent Activity - Does your organization have tools and/or processes in place to detect fraudulent activity on customer accounts? Options: Yes, No', 'Yes/No selection for fraudulent activity detection tools and processes', 'detecting fraudulent activity organization tools processes detect customer accounts yes no');
