-- Corrected seed data with exact questions from UBC Excel file and BMO screenshots

-- Clear existing data
DELETE FROM questions;
DELETE FROM categories;

-- Insert categories
INSERT INTO categories (name, description) VALUES 
('Privacy and Info Security - General', 'General privacy and information security questions'),
('Policies and Privacy Program', 'Questions about policies, procedures, and privacy programs'),
('Internal Access', 'Questions about internal access controls and procedures'),
('Security Controls', 'Technical security controls and measures'),
('Physical Safeguards', 'Physical security measures and safeguards'),
('Operations in the EU & ROW', 'European Union and Rest of World operations'),
('Information Sharing to Other Third Parties', 'Third-party information sharing policies'),
('BMO General', 'BMO General organizational questions'),
('BMO Legal and Regulatory Framework', 'BMO Legal and regulatory compliance questions'),
('BMO Governance Structure', 'BMO Corporate governance and structure questions'),
('BMO Incidents and Findings', 'BMO Security incidents and findings'),
('BMO Training', 'BMO Training and awareness programs'),
('BMO Subcontractor', 'BMO Subcontractor management and oversight'),
('BMO Locations', 'BMO Location and address management'),
('BMO Risk Assessment', 'BMO Various risk assessment categories'),
('BMO Fraud Risk', 'BMO Fraud risk management and controls');

-- UBC Privacy and Info Security - General
INSERT INTO questions (category_id, question_number, question_text, answer_text, keywords) VALUES 
((SELECT id FROM categories WHERE name = 'Privacy and Info Security - General'), '1', 'Does your organization have a CISO assigned?', 'Our Global IT Head is appointed as the Information Security Officer of the organization.', 'CISO chief information security officer organization assigned'),
((SELECT id FROM categories WHERE name = 'Privacy and Info Security - General'), '2', 'Is there a Information Security Management System in place? Does this meet formal standards for your industry (e.g. certifications such as ISO27001 or similar available)? Please provide your Information Security Policy', 'Yes, our ISMS is ISO27001:2022 certified. attach information security policy', 'ISMS information security management system ISO27001 certification policy standards'),
((SELECT id FROM categories WHERE name = 'Privacy and Info Security - General'), '3', 'Will your company store, transmit, or access Personal Information (e.g., information about our customers, employees, agents, and providers)? What type of information?', 'For delivery team', 'personal information PII store transmit access customers employees agents providers'),
((SELECT id FROM categories WHERE name = 'Privacy and Info Security - General'), '4', 'Will your company have access to any of our company''s intellectual property (e.g., logo, copyrights, trademarks, trade secrets, etc.) during the course of the engagement?', 'For delivery team', 'intellectual property IP logo copyrights trademarks trade secrets engagement access'),
((SELECT id FROM categories WHERE name = 'Privacy and Info Security - General'), '5', 'In what jurisdictions does your company collect information?', 'For delivery team', 'jurisdictions collect information data location geography'),
((SELECT id FROM categories WHERE name = 'Privacy and Info Security - General'), '6', 'Do you have a Data Privacy Impact Assessment (DPIA)? Can you provide your Data Privacy Impact Assessment (DPIA) to UBC with this questionnaire.', 'Ram - our DPIA here in PH is conducted on the non-delivery groups handling PH PII data only (HR, Recruitment, etc)', 'DPIA data privacy impact assessment PII HR recruitment Philippines');

-- UBC Policies and Privacy Program
INSERT INTO questions (category_id, question_number, question_text, answer_text, keywords) VALUES 
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '1', 'Does your company have policies, procedures, and training in place to address data privacy and cyber-security expectations and regulations? Please provide copies for review.', 'Yes attach data privacy policy, guidelines', 'policies procedures training data privacy cyber security regulations guidelines'),
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '2', 'Does your company update privacy and security policies, procedures, and training regularly?', 'Yes', 'update privacy security policies procedures training regularly'),
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '3', 'Are all employees required to complete annual information security training?', 'Yes', 'employees required annual information security training mandatory'),
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '4', 'Does your company have a data breach response plan? Please provide a copy for review.', 'For Ram', 'data breach response plan incident management procedure'),
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '5', 'How often does your company review and test their privacy incident and breach management program?', 'Annually', 'review test privacy incident breach management program annually yearly'),
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '6', 'What is your company''s procedure for notifying us of a data breach or other event?', 'The Engagement Manager will notify her counterpart in UBC via email once a data breach or security incident is confirmed to have impact on the client data.', 'procedure notifying data breach security incident engagement manager email client impact'),
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '7', 'Have you experienced any information security breaches in the past three years?', 'No', 'experienced information security breaches past three years history'),
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '8', 'Do you have insurance coverage for information security incidents?', 'For Ram', 'insurance coverage information security incidents cyber liability'),
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '9', 'Do you perform internal security risk assessments?', 'Yes', 'internal security risk assessments vulnerability evaluation'),
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '10', 'Does your company monitor appropriate sources for new government laws, regulations, and directives? Who is responsible for and what actions are taken when new laws, regulations, and directives impact deployed security solutions or technologies?', 'We suscribe to different organizations as relevant sources of information related to government laws and regulations and email alerts are received via email. IT, HR, ISMS would assess impact to Myridius operations and systems and determine actions to be taken to address the requirements.', 'monitor government laws regulations directives compliance legal requirements IT HR ISMS impact assessment'),
((SELECT id FROM categories WHERE name = 'Policies and Privacy Program'), '11', 'Does your company''s legal department review all contracts and service-level agreements for consistency with its policies and procedures for data privacy and cyber-security?', 'Yes', 'legal department review contracts service level agreements SLA consistency policies procedures data privacy cyber security');

-- UBC Internal Access
INSERT INTO questions (category_id, question_number, question_text, answer_text, keywords) VALUES 
((SELECT id FROM categories WHERE name = 'Internal Access'), '1', 'Please explain how your company determines who has access to each specific class of information. Is information access granted to individuals based on a need-to-know basis?', 'All users are assigned a unique Active Directory user account linked to their employee ID. Group memberships (e.g., security groups, distribution lists) are aligned with the user''s job role and least-privilege principle.', 'access control information classification need to know Active Directory user account employee ID security groups least privilege'),
((SELECT id FROM categories WHERE name = 'Internal Access'), '2', 'Are all employees involved in processing customer data appropriately trained on privacy policies and data handling procedures?', 'Yes', 'employees processing customer data trained privacy policies data handling procedures'),
((SELECT id FROM categories WHERE name = 'Internal Access'), '3', 'How do you verify the identity of those accessing data at your company?', 'An authorization mechanism that controls the privileges granted to each user is required for all Myridius systems. The Myridius Project Manager for the client engagement is responsible for ensuring that each individual system''s governed role matches the privileges that user is entitled to receive. Users will only be given sufficient rights to all systems to enable them to perform their job function. User rights will be kept to a minimum at all times.', 'verify identity accessing data authorization mechanism privileges user rights job function minimum access project manager'),
((SELECT id FROM categories WHERE name = 'Internal Access'), '4', 'Does your company require employees and contractors to sign confidentiality and data security agreements?', 'Yes, it is incorporated in our employmen agreement template.', 'employees contractors confidentiality data security agreements employment template NDA'),
((SELECT id FROM categories WHERE name = 'Internal Access'), '5', 'Are security activity and violations logged and reported?', 'Yes.', 'security activity violations logged reported monitoring audit trail'),
((SELECT id FROM categories WHERE name = 'Internal Access'), '6', 'Does your company maintain a codified process for immediate disabling or modification of access when a temporary employee, contractor, or third party''s status changes (e.g., termination, transfer, end of contract)?', 'For Ram', 'codified process disabling modification access temporary employee contractor third party termination transfer contract'),
((SELECT id FROM categories WHERE name = 'Internal Access'), '7', 'Does your company have procedures in place to securely dispose of sensitive information, regardless of how it is stored (paper, disk, etc.)?', 'Yes', 'procedures securely dispose sensitive information paper disk storage media destruction');

-- UBC Security Controls
INSERT INTO questions (category_id, question_number, question_text, answer_text, keywords) VALUES 
((SELECT id FROM categories WHERE name = 'Security Controls'), '1', 'Does your company have a formal IT department? A full-time information security staff?', 'Yes', 'formal IT department full time information security staff dedicated team'),
((SELECT id FROM categories WHERE name = 'Security Controls'), '2', 'What media will you use to store electronic sensitive information on our behalf?', 'For Ram', 'media store electronic sensitive information storage devices systems'),
((SELECT id FROM categories WHERE name = 'Security Controls'), '3', 'Where, physically, will any data containing electronic information be located? (on-site location, SaaS, cloud) please specify region', 'For Ram', 'physically data electronic information located on site SaaS cloud region geography'),
((SELECT id FROM categories WHERE name = 'Security Controls'), '4', 'Can your company provide evidence that it has the controls in place to ensure data collection, access, management, security, and retention is done properly and in accordance with the appropriate laws and regulations?', 'Yes', 'evidence controls data collection access management security retention laws regulations compliance'),
((SELECT id FROM categories WHERE name = 'Security Controls'), '5', 'What is your encryption policy?', 'Access to RCG information systems shall be encrypted. Users will be given application/protocol access with the current encryption algorithm that is defined based on Myridius standards. Hard disk using SSD technology are encrypted by default. In addition, BitLocker should be installed on laptops.', 'encryption policy RCG information systems encrypted application protocol algorithm SSD BitLocker laptops'),
((SELECT id FROM categories WHERE name = 'Security Controls'), '6', 'Do you employ firewalls to protect systems that may contain sensitive information?', 'Yes', 'firewalls protect systems sensitive information network security perimeter'),
((SELECT id FROM categories WHERE name = 'Security Controls'), '7', 'Do you require the use of security tokens or unique user IDs, strong passwords to access PII, password-activated screen savers, and automatic log-off features on your computers?', 'Yes', 'security tokens unique user IDs strong passwords PII password activated screen savers automatic log off computers'),
((SELECT id FROM categories WHERE name = 'Security Controls'), '8', 'Is anti-virus software installed on your e-mail gateways, servers, desktops, and laptops?', 'Yes', 'anti virus software email gateways servers desktops laptops malware protection'),
((SELECT id FROM categories WHERE name = 'Security Controls'), '9', 'Do you conduct internal audits on technology controls currently in place?', 'Yes', 'internal audits technology controls audit assessment review'),
((SELECT id FROM categories WHERE name = 'Security Controls'), '10', 'Does your company have measures in place to address data that is lost or that becomes temporarily unavailable? Please provide details', 'For Ram', 'measures data lost temporarily unavailable backup recovery disaster continuity');

-- UBC Physical Safeguards
INSERT INTO questions (category_id, question_number, question_text, answer_text, keywords) VALUES 
((SELECT id FROM categories WHERE name = 'Physical Safeguards'), '1', 'Are all physical entry points to your facility protected against unauthorized entry by locks, card readers, guards, etc.?', 'Yes', 'physical entry points facility protected unauthorized entry locks card readers guards access control'),
((SELECT id FROM categories WHERE name = 'Physical Safeguards'), '2', 'Is all visitor and vendor access to your company''s facility logged to maintain a physical audit trail of visitor activity?', 'Yes', 'visitor vendor access facility logged physical audit trail visitor activity monitoring'),
((SELECT id FROM categories WHERE name = 'Physical Safeguards'), '3', 'Where will your company store hard-copy sensitive information?', 'Hardcopy sensitive information are kept in locked filing cabinets that are inside a restricted access room.', 'store hard copy sensitive information locked filing cabinets restricted access room physical security'),
((SELECT id FROM categories WHERE name = 'Physical Safeguards'), '4', 'Are physical security measures are in place to protect your company''s information assets? Provide details', 'CCTV on all entrance/ exit of the facilities, proximity card or biometric scan door access, fire extinguishers, door alarms if left open.', 'physical security measures information assets CCTV entrance exit proximity card biometric scan door access fire extinguishers alarms');

-- UBC Operations in the EU & ROW
INSERT INTO questions (category_id, question_number, question_text, answer_text, keywords) VALUES 
((SELECT id FROM categories WHERE name = 'Operations in the EU & ROW'), '1', 'Will you be collecting data from the European Union or other countries outside of the USA?', 'For delivery team', 'collecting data European Union EU countries outside USA international operations'),
((SELECT id FROM categories WHERE name = 'Operations in the EU & ROW'), '2', 'If so, do you comply with the EU-US Privacy Shield Framework?', 'Yes', 'comply EU US Privacy Shield Framework international data transfer'),
((SELECT id FROM categories WHERE name = 'Operations in the EU & ROW'), '3', 'Are you currently in compliance with GDPR? If not, what steps do you have in place to work towards compliance?', 'Yes', 'compliance GDPR General Data Protection Regulation European privacy law');

-- UBC Information Sharing to Other Third Parties
INSERT INTO questions (category_id, question_number, question_text, answer_text, keywords) VALUES 
((SELECT id FROM categories WHERE name = 'Information Sharing to Other Third Parties'), '1', 'Will your company transmit sensitive information to any additional third parties?', 'For delivery team', 'transmit sensitive information additional third parties data sharing'),
((SELECT id FROM categories WHERE name = 'Information Sharing to Other Third Parties'), '2', 'What data privacy and cyber-security requirements does your company require of its third parties (fourth parties)? How will you ensure that appropriate information security safeguards are in place?', 'Signed NDA, Information Security and Data Privacy Awareness Training.', 'data privacy cyber security requirements third parties fourth parties NDA information security data privacy awareness training safeguards');

-- BMO Questions from Screenshots
INSERT INTO questions (category_id, question_number, question_text, answer_text, keywords) VALUES 
((SELECT id FROM categories WHERE name = 'BMO General'), '3.0', 'Change of Scope of Relationship - Since your last Due Diligence assessment, has there been a change in your organization or the products or services provided to BMO? Select all that apply.', 'Options: Change of ownership in the organization, Delivering products or services TO a different Country, Delivering products or services FROM a different Country, Products and/or services added or removed, No Change in Scope of products or services provided', 'change scope relationship due diligence assessment organization products services BMO ownership country'),

((SELECT id FROM categories WHERE name = 'BMO Legal and Regulatory Framework'), '4.0', 'Legal and Regulatory Framework - Select all that are applicable to your organization''s governance structure.', 'Governance Structure options: Independent Board of Directors, Independent audit group, Issues Management Policy, Material Issues/breaches reported to the BOD, Complaints Management Program, None of the above', 'legal regulatory framework governance structure independent board directors audit group issues management policy BOD complaints'),

((SELECT id FROM categories WHERE name = 'BMO Legal and Regulatory Framework'), '4.0', 'Select all that are applicable to your organization''s Legal & Regulatory Framework.', 'Legal & Regulatory Framework options: Inventory of all laws and regulations applicable to the company, Compliance report to ensure all laws and regulations met, Data privacy assessments or ongoing monitoring relating to privacy controls, Domain Leads (i.e. Regulatory or Compliance Officers) that keep track of HR regulations/regulation changes in the jurisdiction(s) in which you operate and ensure these changes are appropriately implemented by the respective business units to ensure compliance, Company does not have a Legal & Regulatory framework', 'legal regulatory framework laws regulations compliance data privacy assessments domain leads officers HR jurisdiction'),

((SELECT id FROM categories WHERE name = 'BMO Legal and Regulatory Framework'), '4.0', 'Is your organization subject to regulatory agency oversight?', 'Regulatory Oversight options: Yes, No', 'organization subject regulatory agency oversight'),

((SELECT id FROM categories WHERE name = 'BMO Legal and Regulatory Framework'), '4.0.1', 'Legal and Regulatory Framework - No Policies and/or Procedures - Explain why you do not maintain any policies and procedures.', 'Not Applicable', 'legal regulatory framework no policies procedures explain maintain'),

((SELECT id FROM categories WHERE name = 'BMO Governance Structure'), '4.1.1', 'Governance Structure Artifacts - For the Governance Structure question, provide supporting artifacts for each item selected as evidence.', 'Upload supporting artifacts', 'governance structure artifacts evidence supporting documents upload'),

((SELECT id FROM categories WHERE name = 'BMO Incidents and Findings'), '5.0', 'Incidents and Findings - Since your last assessment, has your organization or any subcontractor encountered any of the following issues or incidents? Select all that apply.', 'Options: An unauthorized or improper collection, use, disclosure of Personal Information in the last 24 months, Physical or Information Security Incidents / Privacy breach, Identified material data loss (i.e. data corruption or Integrity Issues) that impacted Service Level Agreements to BMO, Material issues or changes related to Digital, AI, or Robotic Process Automation (RPA), Emerging Technology applications or services that impact the trustworthiness rating/assessment, You or your directors, officers or employees have been suspected of/investigated for violating anti-bribery and anti-corruption laws by a court, public agency, or regulatory body, Privacy-related regulatory findings or privacy-related legal action taken against your firm, Experienced outages or service disruptions in the last 12 months, None of the above', 'incidents findings assessment organization subcontractor unauthorized improper collection personal information security incidents privacy breach data loss corruption integrity service level agreements digital AI robotic process automation RPA emerging technology trustworthiness anti-bribery corruption regulatory findings legal action outages service disruptions'),

((SELECT id FROM categories WHERE name = 'BMO Training'), '6.0', 'Training - Does your organization maintain a mandatory annual training curriculum on any of the following subjects? Select all that apply.', 'Training subjects: Fraud, Fair Credit Reporting Act, Privacy, Information Security, and/or Cybersecurity Awareness, Ethical AI Awareness (i.e. Fair, Accountable, Transparent, Trusted), None of the above', 'training organization mandatory annual curriculum fraud fair credit reporting act privacy information security cybersecurity awareness ethical AI fair accountable transparent trusted'),

((SELECT id FROM categories WHERE name = 'BMO Subcontractor'), '7.0', 'Subcontractor Information - Depending on your specific contractual agreement, BMO''s Third-Parties may use Subcontractors (your organization''s Third-Parties) to deliver some of the products or services to BMO. BMO requires awareness of your use of Subcontractors. Subcontractors are broadly defined to include the firm Subcontractors, consultants, agents, sales representatives or other parties your organization might engage to deliver the products or services to BMO.', 'Throughout this program Subcontractor refers to your organization''s Third-Parties. Please only consider Subcontractors used in the delivery of products or services to BMO.', 'subcontractor information contractual agreement BMO third parties deliver products services awareness consultants agents sales representatives'),

((SELECT id FROM categories WHERE name = 'BMO Subcontractor'), '7.1.10', 'Not Using Subcontractors - We currently have on file that you are not using Subcontractors to deliver the products or services to BMO.', 'Since the last review have you retained or hired parties such as Subcontractors, consultants, agents or sales representatives in connection with providing the products or services to BMO? Options: Yes, No', 'not using subcontractors file deliver products services BMO retained hired parties consultants agents sales representatives'),

((SELECT id FROM categories WHERE name = 'BMO Locations'), '8.0.1', 'Review/Update Third-Party and Subcontractor Addresses - Shown below in section 8.2 are location/address details for all of your organization and subcontractor Primary and Backup locations used to provide the products or services to BMO under this arrangement. Please review the information within the location object by clicking on edit and make any updates as necessary.', 'Review and update location/address details for organization and subcontractor locations', 'review update third party subcontractor addresses location details organization primary backup locations products services BMO arrangement'),

((SELECT id FROM categories WHERE name = 'BMO Locations'), '8.0.3', 'Review/Update Subcontractor Addresses - A Subcontractor''s product or service has a degree of importance to your business operations utilized under this arrangement or is an outsourced business process in the provision of the product/service arrangement to BMO.', 'How many Primary Subcontractor sites are there in total to provide products or services to BMO under this contractual agreement? How many Backup Subcontractor sites are there in total to provide products or services to BMO under this contractual agreement?', 'review update subcontractor addresses product service degree importance business operations outsourced process primary backup sites contractual agreement'),

((SELECT id FROM categories WHERE name = 'BMO Locations'), '8.0.4', 'Review/Update Third-Party Addresses - How many Primary Third-Party sites (for your organization, inclusive of headquarter location) are there in total to provide products or services to BMO under this contractual agreement? How many Backup Third-Party sites (for your organization) are there in total to provide products or services to BMO under this contractual agreement?', 'Primary Third-Party Sites: 1, Backup Third-Party Sites: 0', 'review update third party addresses primary backup sites organization headquarter location contractual agreement BMO'),

((SELECT id FROM categories WHERE name = 'BMO Locations'), '8.2', 'Location/Address Listing - A file must be completed for each location indicated in sections 8.0.1 and 8.0.4. You can do the following for the locations listed below. For each location/address answer all required questions.', 'Add new locations, Edit existing locations, Set status to Inactive, Review information and make updates. Location details include: Location Name, Location Type, Third-Party vs Subcontractor Location, Location Status', 'location address listing file completed sections add new locations edit existing set status inactive review information location name type third party subcontractor status'),

((SELECT id FROM categories WHERE name = 'BMO Risk Assessment'), '12.0.1', 'ABAC Risk - Anti Bribery And Corruption (ABAC) is not in scope for this Assessment', 'Anti Bribery And Corruption (ABAC) is not in scope for this Assessment', 'ABAC risk anti bribery corruption not in scope assessment'),

((SELECT id FROM categories WHERE name = 'BMO Risk Assessment'), '13.0.1', 'AML Risk - Anti Money Laundering Risk (AML) is not in scope for this Assessment', 'Anti Money Laundering Risk (AML) is not in scope for this Assessment', 'AML risk anti money laundering not in scope assessment'),

((SELECT id FROM categories WHERE name = 'BMO Risk Assessment'), '14.0.1', 'BCM Risk - Business Continuity Risk (BCM) is not in scope for this Assessment', 'Business Continuity Risk (BCM) is not in scope for this Assessment', 'BCM risk business continuity not in scope assessment'),

((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.2', 'Fraud Risk - Fraud Risk is when a Third-Party is able to use illegal and deceptive means to obtain BMO''s money, assets, property, information or other gains. Fraud risk is present when Third-Parties have access premises, employees, customers, and information. Failure of Third-Parties to meet regulatory requirements or breaching contract terms for other risk areas can result in a fraudulent scenario.', 'Fraud Risk definition and explanation', 'fraud risk third party illegal deceptive means obtain BMO money assets property information gains access premises employees customers regulatory requirements breaching contract fraudulent scenario'),

((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.1', 'Fraud Risk Questions - Does your organization maintain a background check policy, procedure, or standard that requires the performance of background checks on all employees and subcontractors? Does your organization have an ongoing process to ensure that employees have not been convicted of, placed in a pre-trial diversion program, or accepted responsibility (e.g., through a plea bargain) for any crime involving fraud, theft, dishonesty, breach of trust or a violent act since the hiring background check was completed?', 'Background check policy options: Yes, No. Ongoing process options: Yes, No', 'fraud risk questions organization maintain background check policy procedure standard performance employees subcontractors ongoing process convicted pre-trial diversion program accepted responsibility plea bargain crime fraud theft dishonesty breach trust violent act hiring'),

((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.1', 'Does your organization have Policies/Processes/Training for managing fraud (i.e., does your firm have a Code of Ethics/Code of Conduct or a Fraud Management Policy)? Does your organization currently have any of these processes in place? Select all that apply.', 'Fraud management options: Yes, No. Processes: Logical Access, Segregation of Duty, Supervisory Review, Reconciliation, None of the Above', 'organization policies processes training managing fraud code ethics conduct fraud management policy logical access segregation duty supervisory review reconciliation'),

((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.1.1', 'Fraud - Background Check Policies - Please provide evidence of the Background check policy, procedure, or standard that covers employees and Subcontractors.', 'Upload background check policy evidence', 'fraud background check policies provide evidence policy procedure standard covers employees subcontractors upload'),

((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.1.3', 'Fraud - Management Policy & Training Curriculum - Please provide your Fraud Management Policy and Fraud Training Curriculum.', 'Upload fraud management policy and training curriculum', 'fraud management policy training curriculum provide upload'),

((SELECT id FROM categories WHERE name = 'BMO Fraud Risk'), '16.1.5', 'Detecting Fraudulent Activity - Does your organization have tools and/or processes in place to detect fraudulent activity on customer accounts?', 'Fraudulent activity detection options: Yes, No', 'detecting fraudulent activity organization tools processes detect customer accounts');
